# Generated by Django 4.0.1 on 2022-02-05 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.AddField(
            model_name='message',
            name='d',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
