# Generated by Django 4.0.1 on 2022-02-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.CharField(default='05-02-2022', max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default='08:02:34 PM', max_length=30),
        ),
    ]
