# Generated by Django 4.0.1 on 2022-02-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_message_date_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.CharField(default='05/02/2022', max_length=30),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(default='08:03:14 PM', max_length=30),
        ),
    ]
