# Generated by Django 4.0.1 on 2022-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_message_date_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.CharField(max_length=15),
        ),
    ]
